name: Test and Deploy to Repo B

on:
  push:
    branches:
      - main   # or your main branch

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository A
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd ca2
          npm install

      - name: Run Jest tests
        run: |
          cd ca2
          npm test -- --ci

      - name: Build static site
        run: |
          cd ca2
          npm run build
      
      - name: Deploy to Repository B
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: DavidEkpechue/ca2-deploy
          publish_dir: ./ca2/dist
          publish_branch: main   
          personal_token: ${{ secrets.CA2 }}
